package com.custom.mall.domain;

import static com.custom.mall.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class FlashSaleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlashSaleAllPropertiesEquals(FlashSale expected, FlashSale actual) {
        assertFlashSaleAutoGeneratedPropertiesEquals(expected, actual);
        assertFlashSaleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlashSaleAllUpdatablePropertiesEquals(FlashSale expected, FlashSale actual) {
        assertFlashSaleUpdatableFieldsEquals(expected, actual);
        assertFlashSaleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlashSaleAutoGeneratedPropertiesEquals(FlashSale expected, FlashSale actual) {
        assertThat(expected)
            .as("Verify FlashSale auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlashSaleUpdatableFieldsEquals(FlashSale expected, FlashSale actual) {
        assertThat(expected)
            .as("Verify FlashSale relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e ->
                assertThat(e.getStartTime())
                    .as("check startTime")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getStartTime())
            )
            .satisfies(e ->
                assertThat(e.getEndTime()).as("check endTime").usingComparator(zonedDataTimeSameInstant).isEqualTo(actual.getEndTime())
            )
            .satisfies(e -> assertThat(e.getDiscountRate()).as("check discountRate").isEqualTo(actual.getDiscountRate()))
            .satisfies(e -> assertThat(e.getMaxQuantity()).as("check maxQuantity").isEqualTo(actual.getMaxQuantity()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlashSaleUpdatableRelationshipsEquals(FlashSale expected, FlashSale actual) {
        // empty method
    }
}
