package com.custom.mall.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ShopUserAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShopUserAllPropertiesEquals(ShopUser expected, ShopUser actual) {
        assertShopUserAutoGeneratedPropertiesEquals(expected, actual);
        assertShopUserAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShopUserAllUpdatablePropertiesEquals(ShopUser expected, ShopUser actual) {
        assertShopUserUpdatableFieldsEquals(expected, actual);
        assertShopUserUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShopUserAutoGeneratedPropertiesEquals(ShopUser expected, ShopUser actual) {
        assertThat(expected)
            .as("Verify ShopUser auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShopUserUpdatableFieldsEquals(ShopUser expected, ShopUser actual) {
        assertThat(expected)
            .as("Verify ShopUser relevant properties")
            .satisfies(e -> assertThat(e.getUsername()).as("check username").isEqualTo(actual.getUsername()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShopUserUpdatableRelationshipsEquals(ShopUser expected, ShopUser actual) {
        // empty method
    }
}
